import { useState, type KeyboardEvent } from 'react';
import { Send } from 'lucide-react';

interface ChatInputProps {
  onSendMessage: (message: string) => void;
  disabled?: boolean;
}

export default function ChatInput({ onSendMessage, disabled = false }: ChatInputProps) {
  const [message, setMessage] = useState('');

  const handleSubmit = () => {
    if (message.trim() && !disabled) {
      onSendMessage(message.trim());
      setMessage('');
    }
  };

  const handleKeyPress = (e: KeyboardEvent<HTMLTextAreaElement>) => {
    if (e.key === 'Enter' && !e.shiftKey) {
      e.preventDefault();
      handleSubmit();
    }
  };

  return (
    <div className="space-y-2">
      <div className="relative">
        <textarea
          value={message}
          onChange={(e) => setMessage(e.target.value)}
          onKeyPress={handleKeyPress}
          placeholder="Ask about cloud strategies, technical solutions, or the CICP program..."
          className="w-full resize-none rounded-lg border border-[var(--color-border)] bg-[var(--color-surface)] p-4 pr-12 text-[var(--color-text-primary)] placeholder:text-[var(--color-text-muted)] focus:border-transparent focus:outline-none focus:ring-2 focus:ring-[var(--color-highlight)]"
          rows={3}
          disabled={disabled}
        />
        <button
          onClick={handleSubmit}
          disabled={!message.trim() || disabled}
          className={`absolute bottom-5 right-4 rounded-md p-2 transition-colors ${
            message.trim() && !disabled
              ? 'bg-[var(--color-highlight)] text-white hover:bg-[var(--color-highlight-soft)]'
              : 'cursor-not-allowed bg-[var(--color-border)] text-[var(--color-text-muted)]'
          }`}
          aria-label="Send message"
        >
          <Send className="w-5 h-5" />
        </button>
      </div>
      
      {/* Disclaimer */}
      <p className="text-xs text-center text-[var(--color-text-secondary)]">
        This chatbot uses RAG on CICP knowledge base. Responses are generated by AI and should be verified.
      </p>
    </div>
  );
}