export const chatInputContent = {
  placeholder: "Ask about cloud strategies, technical solutions, or the CICP program...",
  disclaimer: "This chatbot uses RAG on research and education cloud community activities. Responses are generated by AI and should be verified.",
  sendButtonLabel: "Send message"
};
